### ISSUE TITLE
!!!111First: Mudar icone e mascote

### ISSUE THREAD

**Issue by matheusd** [Bolagato-Finance/bolagato#1]
Sugestão (o da direita): https://pixabay.com/vectors/rabbit-cat-animal-cute-manga-4268123/

**Comment by matheusd** [comment]
Ou se tiver alguém aí que puder contribuir um ícone personalizado...

**Comment by girino** [comment]
Dada a origem da moeda no grupo de Stalinismo Anarcocapitalista, usamos a bandeira Stancap como icone! Vou fechar essa issue.
